# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 14:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=256)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=32)),
                ('user_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('register_date',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('register_token', models.CharField(max_length=8)),
                ('group_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=32)),
                ('tilawah_count', models.IntegerField(default=0)),
                ('tilawah_miss', models.IntegerField(default=0)),
                ('tilawah_day', django.contrib.postgres.fields.jsonb.JSONField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.Group')),
            ],
            options={
                'ordering': ('register_date',),
            },
        ),
        migrations.AddField(
            model_name='group',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responder.Organization'),
        ),
    ]
